version: 2
jobs:
  build:
    docker:
      - image: ubuntu:17.04
    environment:
      DOCKER_VER: 17.03.0-ce
      DOCKER_USER: bloo
      PROJECT: bloo/journalbeat
      TAG_MAJOR: 0.1
    working_directory: /build
    steps:
      - run: apt-get update && apt-get install -y curl git
      - checkout
      - setup_docker_engine
      # use a primary image and install docker
      - run:
          name: Install Docker client
          command: |
            set -x
            curl -L -o /tmp/docker-${DOCKER_VER}.tgz https://get.docker.com/builds/Linux/x86_64/docker-${DOCKER_VER}.tgz
            tar -xz -C /tmp -f /tmp/docker-${DOCKER_VER}.tgz
            mv /tmp/docker/* /usr/bin
      # build and push Docker image, in remote docker engine env
      - run:
          name: Build and Install
          command: |
            TAG=${TAG_MAJOR}.${CIRCLE_BUILD_NUM}
            docker build -t ${PROJECT}:${TAG} .
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker push ${PROJECT}:${TAG}
